In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

1. Introduction to NumPy and Array Creation (10 Marks)
    Create a 1D NumPy array with the elements [10, 20, 30, 40, 50]. (2 Marks)
    Create a 2D array of shape (2, 3) using numpy.zeros. (3 Marks)
    Use numpy.linspace to create an array of 5 evenly spaced numbers between 0 and 100. (5 Marks)


In [32]:
import numpy as np
#1d create
onedarray=np.array([10,20,30,40,50])
print(onedarray)
#2d create
twodarray=np.zeros((2,3))
print(twodarray)
#linspace
linespace=np.linspace(0,100,5)
print(linespace)


[10 20 30 40 50]
[[0. 0. 0.]
 [0. 0. 0.]]
[  0.  25.  50.  75. 100.]


2. Array Indexing and Slicing (10 Marks)
Using the 1D array [5, 10, 15, 20, 25, 30]:
Extract the first 3 elements. (2 Marks)
Extract every second element. (3 Marks)
Change the 4th element to 50 and print the updated array. (5 Marks)


In [38]:
import numpy as np 
arrar=np.array([5,10,15,20,25,30])
#first 3
first=arrar[:3]
print(first)
#every 2nd
second=arrar[1::2]
print(second)
#change and update
arrar[3]=50
print(arrar)

[ 5 10 15]
[10 20 30]
[ 5 10 15 50 25 30]


3. Reshaping Arrays (10 Marks)
Create a 1D array with 12 elements ranging from 1 to 12 using numpy.arange. (5 Marks)
Reshape it into a 2D array of shape (3, 4). (5 Marks)


In [39]:
import numpy as np 
#1d 
num=np.arange(12)
print(num)
#2d with reshape
renum=num.reshape(3,4)
print(renum)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


4. Broadcasting and Element-wise Operations (10 Marks)
Create a 1D array with elements [1, 2, 3, 4, 5].
Perform the following operations:
Add 10 to each element. (2 Marks)
Multiply each element by 3. (3 Marks)
Calculate the square of each element. (5 Marks)


In [47]:
import numpy as np 
array=np.array([1,2,3,4,5])
b=np.array([10])
#add 
add=np.add(array,b)
print(add)
#multiply
multi=np.array([3])
multiply=np.multiply(array,multi)
print(multiply)
#sqare
sqare=np.multiply(array,array)
print(sqare)

[11 12 13 14 15]
[ 3  6  9 12 15]
[ 1  4  9 16 25]


5. Basic Statistics with Arrays (10 Marks)
Create a NumPy array representing daily temperatures for a week: [30, 32, 31, 29, 28, 33, 34].
Find the mean temperature of the week. (3 Marks)
Find the minimum and maximum temperatures. (3 Marks)
Calculate the total sum of the temperatures. (4 Marks)


In [48]:
import numpy as np  
tem=np.array([30,32,31,29,28,33,34
#mean tem
mean=np.mean(tem)
print(mean)
#min and max tep
min=np.min(tem)
max=np.max(tem)
print(min,"and", max)
#total sum of temp
sum=np.sum(tem)
print(sum)

31.0
28 and 34
217


6. Real-World Problem: Sales Analysis (10 Marks)
Create a 2D array representing sales data for 2 products over 5 days:
less
Copy code
Product 1: [200, 220, 250, 270, 300]  
Product 2: [150, 160, 170, 180, 200]  


Calculate the total sales for each product. (4 Marks)
Calculate the average sales per day. (3 Marks)
Find the day with the highest sales for each product. (3 Marks)


In [60]:
import numpy as np 
array=np.array([[200,220,250,270,300],[150,160,170,180,200]])
print(array)
#totalsellsforeachproduct
sum=np.sum(array,axis=1)
print(sum)
#averagesell
average=np.mean(array,axis=0)
print(average)
#highest sell
highestsell=np.argmax(array,axis=1)+1
print(highestsell)

[[200 220 250 270 300]
 [150 160 170 180 200]]
[1240  860]
[175. 190. 210. 225. 250.]
[5 5]
